# Generated by Django 2.1.7 on 2019-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    migrations.CreateModel(
            name='Deliverydtails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deliverydate', models.DateField()),
                ('Trackingno', models.CharField(max_length=200)),
                ('Packingstatus', models.CharField(max_length=200)),
                ('Shippingstatus', models.CharField(max_length=200)),
                ('Delivery_status', models.CharField(max_length=200)),
            ],
        ),
    migrations.CreateModel(
            name='ExchangeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchngname', models.CharField(default='', max_length=200)),
                ('dscrptn', models.CharField(max_length=500)),
                ('discount', models.IntegerField()),
                ('Start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('coupon_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MB_scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schemeno', models.CharField(max_length=200)),
                ('Customer_name', models.CharField(default='', max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Email_Id', models.EmailField(max_length=200)),
                ('Mobileno', models.CharField(max_length=200)),
                ('Month', models.CharField(max_length=200)),
                ('Winner', models.CharField(max_length=200)),
                ('Coupon_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=200, null=True)),
                ('Order_date', models.DateField(blank=True)),
                ('Quantity', models.IntegerField(blank=True)),
                ('Unit_price', models.IntegerField(default='')),
                ('Order_status', models.CharField(max_length=200)),
                ('Items', models.CharField(max_length=200, null=True, blank=True))
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paymenttype', models.CharField(max_length=200)),
                ('BankName', models.CharField(default='', max_length=200)),
                ('BankBranch', models.CharField(max_length=200)),
                ('Couponno', models.CharField(max_length=200)),
                ('Amountpaid', models.IntegerField()),
                ('Paymentdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image1', models.FileField(upload_to='documents/')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('cgst', models.IntegerField()),
                ('sgst', models.IntegerField()),
                ('total', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Purchase_date', models.DateField()),
                ('Total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(default='', max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('Price', models.IntegerField()),
                ('Service_men_name', models.CharField(default='', max_length=200)),
                ('Service_men_Mbno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('cgst', models.IntegerField()),
                ('sgst', models.IntegerField()),
                ('transport_charges', models.IntegerField()),
                ('sdate', models.DateField()),
                ('total', models.IntegerField()),
                ('sold_out', models.IntegerField()),
                ('availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('product_name', models.CharField(default='', max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='', max_length=200)),
                ('Lastname', models.CharField(default='', max_length=200)),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=400)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField()),
                ('MobileNumber', models.CharField(max_length=10)),
                ('EmailID', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('ConfirmPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('order_id', models.IntegerField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('gst', models.IntegerField(null=True, blank=True)),
                ('total', models.IntegerField(null=True, blank=True)),
                ('shipping_charges', models.IntegerField(null=True, blank=True)),
                ('grand_total', models.IntegerField(null=True, blank=True)),
                ('total_tax', models.IntegerField(null=True, blank=True)),
            ],
        ),
    ]
