# Generated by Django 2.1.7 on 2019-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappliance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='Order_status',
        ),
        migrations.AddField(
            model_name='order_details',
            name='Total',
            field=models.IntegerField(null=True),
        ),
    ]
