# Generated by Django 2.1.7 on 2019-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappliance_app', '0002_auto_20190312_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default='', max_length=200, null=True)),
                ('customer_id', models.IntegerField(default='', max_length=200, null=True)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('gst', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('shipping_charges', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order_details',
            name='Order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='Unit_price',
            field=models.IntegerField(default='', null=True),
        ),
    ]
