# Generated by Django 2.1.7 on 2019-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappliance_app', '0003_auto_20190313_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='Items',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='customer_id',
            field=models.IntegerField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='billing',
            name='order_id',
            field=models.IntegerField(default='', max_length=200),
        ),
    ]
