# Generated by Django 2.1.7 on 2019-03-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappliance_app', '0006_auto_20190314_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pbilling',
            new_name='billing',
        ),
    ]
