# Generated by Django 2.1.7 on 2019-03-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappliance_app', '0007_auto_20190314_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='bill_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='order_id',
        ),
    ]
