# Generated by Django 2.1.7 on 2019-03-14 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myappliance_app', '0009_auto_20190314_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='customer_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='billing',
            name='gst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='order_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='billing',
            name='shipping_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='total_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
