# Generated by Django 2.1.7 on 2019-04-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappliance_app', '0013_auto_20190315_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=200)),
                ('productname', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(default='', max_length=200)),
                ('unitprice', models.IntegerField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='billing',
        ),
        migrations.DeleteModel(
            name='Deliverydtails',
        ),
        migrations.DeleteModel(
            name='ExchangeOffer',
        ),
        migrations.DeleteModel(
            name='MB_scheme',
        ),
        migrations.DeleteModel(
            name='Order_details',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ProCategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase_Items',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='StockItems',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
