# Generated by Django 2.1.7 on 2019-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappliance_app', '0014_auto_20190403_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(blank=True, null=True)),
                ('customersid', models.EmailField(blank=True, max_length=254, null=True)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('items', models.CharField(default='', max_length=200)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('gst', models.IntegerField(blank=True, null=True)),
                ('tax_total', models.IntegerField(blank=True, null=True)),
                ('shipping_charge', models.IntegerField(blank=True, null=True)),
                ('grandtotal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverydtails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deliverydate', models.DateField(auto_now_add=True)),
                ('Trackingno', models.CharField(max_length=200)),
                ('Packingstatus', models.CharField(max_length=200)),
                ('Shippingstatus', models.CharField(max_length=200)),
                ('Delivery_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchngname', models.CharField(default='', max_length=200)),
                ('dscrptn', models.CharField(max_length=500)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('Start_date', models.DateField(auto_now_add=True)),
                ('finish_date', models.DateField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.EmailField(max_length=200)),
                ('servicefeedback', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MB_scheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Schemeno', models.CharField(max_length=200)),
                ('Customer_name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Email_Id', models.EmailField(max_length=200)),
                ('Mobileno', models.CharField(max_length=200)),
                ('Month', models.CharField(max_length=200)),
                ('Winner', models.CharField(max_length=200)),
                ('Coupon_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitprice', models.IntegerField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('uid', models.CharField(max_length=50, null=True)),
                ('items', models.CharField(max_length=50, null=True)),
                ('Amonth', models.IntegerField(blank=True, null=True)),
                ('Ayear', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paymenttype', models.CharField(default='', max_length=200)),
                ('BankName', models.CharField(default='', max_length=200)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Paymentdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image1', models.FileField(upload_to='documents/')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('gst', models.IntegerField(blank=True, null=True)),
                ('cgst', models.IntegerField(blank=True, null=True)),
                ('sgst', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitem', models.CharField(default='', max_length=200)),
                ('pprice', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Purchase_date', models.DateField(auto_now_add=True)),
                ('Total_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(default='', max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Service_men_name', models.CharField(default='', max_length=200)),
                ('Service_men_Mbno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=200)),
                ('Itemname', models.CharField(max_length=200)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('gst', models.IntegerField(blank=True, null=True)),
                ('cgst', models.IntegerField(blank=True, null=True)),
                ('sgst', models.IntegerField(blank=True, null=True)),
                ('transport_charges', models.IntegerField(blank=True, null=True)),
                ('sdate', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('sold_out', models.IntegerField(blank=True, null=True)),
                ('availability', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(default='', max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='', max_length=200)),
                ('Lastname', models.CharField(default='', max_length=200)),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=400)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('EmailID', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('ConfirmPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
